Fixed buffer overflow in rdlog
edenhill/librd pull request #12
Opened 2015-05-21 11:23 UTC by eugpermar

2015-06-02 09:30 UTC, eugpermar commented
* Changed rdlog logic (sorry about delay)
* Achieved rd_memctx_t _F_TRACK individual chunk free

2019-01-18 21:19 UTC, eugpermar commented
Hi! It's been a long time since this PR with many improvements I need to add to librd in order to work properly in my projects.

I just add a few changes to make it compile on clang-7 default settings. I could cherry-pick only the changes you are interested in (of all of them) and merge them separately (https://github.com/edenhill/librd/pull/12/commits).

Regards!

2019-01-21 13:23 UTC, edenhill requested changes

2019-01-21 14:56 UTC, eugpermar commented on rdavl.h
> +	rd_avl_foreach(ravl, callback, opaque, 1);
ouch! Solved!

2019-01-23 16:49 UTC, merged

2019-01-23 16:49 UTC, edenhill commented
Sweet thanks!

2019-01-23 18:42 UTC, eugpermar commented
Thank you! :)